import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar";
// Temporarily disabled due to Next.js 15 compatibility issues
// import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
// import { extractRouterConfig } from "uploadthing/server";
// import { ourFileRouter } from "./api/uploadthing/core";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Temporarily disabled due to Next.js 15 compatibility issues */}
        {/* <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} /> */}
        <Navbar />
        {children}
        <Toaster richColors theme="light" closeButton />
      </body>
    </html>
  );
}
