import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import { Footer } from "./components/Footer";
import { MobileBottomNav } from "./components/MobileBottomNav";
// import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
// import { extractRouterConfig } from "uploadthing/server";
// import { ourFileRouter } from "./api/uploadthing/core";
import { Toaster } from "@/components/ui/sonner";
import { Suspense } from "react";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import { getCurrentUser } from "@/lib/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// async function UTSSRComponent() {
//   // For React 19 and Next.js 15 compatibility
//   return <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />;
// }

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { getUser } = getKindeServerSession();
  const kindeUser = await getUser();
  const user = await getCurrentUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Suspense fallback={null}>
          <UTSSRComponent />
        </Suspense> */}
        <Navbar />
        <div className="pb-20 lg:pb-0">
          {children}
        </div>
        <Footer />
        <MobileBottomNav 
          user={kindeUser ? {
            email: kindeUser.email as string,
            name: kindeUser.given_name as string,
            userImage: (user as any)?.homeownerProfile?.profilePicture || 
                       (user as any)?.housemateProfile?.profilePicture || 
                       (kindeUser.picture ?? `https://avatar.vercel.sh/${kindeUser.given_name}`),
            userType: (user as any)?.userType || null
          } : null}
        />
        <Toaster richColors theme="light" closeButton />
      </body>
    </html>
  );
}
