import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import { Footer } from "./components/Footer";
// import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
// import { extractRouterConfig } from "uploadthing/server";
// import { ourFileRouter } from "./api/uploadthing/core";
import { Toaster } from "@/components/ui/sonner";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// async function UTSSRComponent() {
//   // For React 19 and Next.js 15 compatibility
//   return <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />;
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Suspense fallback={null}>
          <UTSSRComponent />
        </Suspense> */}
        <Navbar />
        {children}
        <Footer />
        <Toaster richColors theme="light" closeButton />
      </body>
    </html>
  );
}
